# Generated by Django 5.1.4 on 2025-01-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bigium_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlecategory",
            old_name="name",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="articlecomment",
            old_name="content",
            new_name="comment",
        ),
    ]
