# Generated by Django 5.1.4 on 2025-01-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bigium_app", "0002_rename_name_articlecategory_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="category",
            new_name="category_id",
        ),
        migrations.RenameField(
            model_name="articlecomment",
            old_name="article",
            new_name="article_id",
        ),
    ]
