# Generated by Django 5.1.4 on 2025-01-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bigium_app", "0003_rename_category_article_category_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="category_id",
            new_name="category",
        ),
    ]
